# Very lightweight combat log
combatlog:
  enabled: true
  disable-elytra: true # Disable elytra in combat
  cooldowns: # Cooldowns to apply in combat
    # Item names in this config use https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    # NBT matching uses substring checks against the item's full component string
    # For NBT data, use https://minecraft.wiki/w/Data_component_format
    # To check exact NBT, use /data get entity @s SelectedItem to see the component structure
    # Format: "key: value" or just "value" if unique enough
    - material: TRIDENT
      duration: 100 # In ticks
      global: false # True = cooldowns also applies outside of combat
      nbt:
        # Matches: minecraft:enchantments={levels:{"minecraft:riptide":1}}
        enchantments: "\"minecraft:riptide\":1"
    - material: TRIDENT
      duration: 200
      global: false
      nbt:
        enchantments: "\"minecraft:riptide\":2"
    - material: TRIDENT
      duration: 300
      global: false
      nbt:
        enchantments: "\"minecraft:riptide\":3"
#   Example of other Component checks
#   - material: STICK
#     duration: 100
#     global: true
#     nbt:
#       custom_model_data: 12345
#       # Note: Strings in components often use single quotes or escaped double quotes
#       custom_name: "'{\"text\":\"Magic Stick\"}'"
    - material: ENDER_PEARL # Different cooldowns in and out of combat
      duration: 40
      global: false
    - material: ENDER_PEARL
      duration: 20
      global: true
    - material: CHORUS_FRUIT
      duration: 200
      global: false
    - material: CHORUS_FRUIT
      duration: 20
      global: true
    - material: WIND_CHARGE
      duration: 40
      global: false

# Whether to drop player heads on death
death-drops:
  enabled: true

# Disable specific effects from being inflicted onto *players*
disabled-potions:
  enabled: true
  effects: # https: //hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
    WEAKNESS: 0 # Maximum allowed level
    SLOW_FALLING: 0

# Disallow specific enchantments on specific items
restricted-enchantments:
  enabled: true
  items: # Priority goes down the list
    MACE: # Item names are inclusive, ie HELMET will apply to every item with helmet in its name
      glint: false # Whether or not to show the enchantment glint
      enchantments:
        DENSITY: 0 # Maximum allowed level
        BREACH: 0
        WIND_BURST: 0
    ELYTRA:
      glint: true
      enchantments:
        MENDING: 0
#   HELMET:
#     glint: true
#     enchantments:
#       PROTECTION: 3
#   GLOBAL: # Global config should be the lowest priority
#     glint: true
#     enchantments:
#       VANISHING_CURSE: 0

# Reduce explosion damage per item
explosion-damage: # Applies before armour damage reduction calculation
  enabled: true
  bed: 0.25 # Multiplier is applied before armour, make sure to check damage in game
  anchor: 0.25
  cart: 0.4
  crystal: 0.25

# System set in place to limit the maximum amount of items players can carry
# When the item limit is exceeded, apply effects to the player
item-limits:
  enabled: true
  scan-bundles: true
  scan-shulkers: false
  scan-echest: false
  message-type: TITLE # ACTION_BAR or TITLE
  text: "You are overencumbered!"
  subtitle: "Drop excess items to move"

  limits:
    - material: TOTEM_OF_UNDYING
      limit: 1
    - material: ENDER_PEARL
      limit: 32
    - material: COBWEB
      limit: 64
    - material: EXPERIENCE_BOTTLE
      limit: 128
  # Group limits (Weighted items)
  groups:
    wind_items:
      limit: 64
      items:
        - material: WIND_CHARGE
          weight: 1
        - material: BREEZE_ROD
          weight: 4
    turtle_master:
      limit: 2
      items:
        - material: POTION
          weight: 2
          nbt:
          potion_contents: "minecraft:strong_turtle_master"
        - material: POTION
          weight: 1
          nbt:
          potion_contents: "minecraft:long_turtle_master"
        - material: POTION
          weight: 1
          nbt:
          potion_contents: "minecraft:turtle_master"

  effects:
    BLINDNESS:
      duration: 40
      amplifier: 3
    SLOWNESS:
      duration: 40
      amplifier: 3
    WEAKNESS:
      duration: 40
      amplifier: 1